### ISSUE TITLE
SRTM SSL Certificate Expired

### ISSUE THREAD

**Issue by qwwqe** [bunburya/bother#8]
Just a heads up that the SSL certificate for [srtm.csi.cgiar.org](https://srtm.csi.cgiar.org) seems to have expired in November and has not been renewed since. This causes the following request to fail with an `ssl.SSLCertVerificationError`:

https://github.com/bunburya/bother/blob/7824fe000b4e4926a41681362bd4cd43350c5884/bother_utils/srtm.py#L60

I've sent an email notifying the site admin, but as a temporary workaround I've just been disabling certificate verification:

`r = requests.get(url, stream=True, verify=False)`

Obviously not secure but it does seem to proceed smoothly otherwise.

By the way, thanks for sharing this. It's pretty cool playing OpenTTD on maps of the region you grew up in.

**Comment by bunburya** [comment]
Thanks for flagging and for reaching out to the site admin - I had reached out to them previously myself. The certificate has been updated now so I will close the issue.
